language: generic
services:
  - docker

before_install:
  - docker build -t krigar1184/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true krigar1184/react-test npm run test

after_success:
  - docker build -t krigar1184/complex-client ./client
  - docker build -t krigar1184/complex-nginx ./nginx
  - docker build -t krigar1184/complex-server ./server
  - docker build -t krigar1184/complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push krigar1184/complex-client
  - docker push krigar1184/complex-nginx
  - docker push krigar1184/complex-server
  - docker push krigar1184/complex-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-course-complex"
  env: "DockerCourseComplex-env"
  bucket_name: "elasticbeanstalk-us-east-2-803441828173"
  bucket_path: "docker-course-complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
